#!/usr/bin/env Rscript

sys = modules::import('klmr/sys')

sys$run({
    args = list(
        design = 'raw/samples.csv',
        coverage_path = 'data/coverage/long',
        annotation = '../shared/annotation/Apis_mellifera.GCA_000002195.1-viruses/Apis_mellifera.GCA_000002195.1.32-viruses.gtf',
        outfile = 'data/coverage/long/vdv1-coverage.pdf'
    )
    rtl = modules::import_package('rtracklayer')
    gr = modules::import_package('GenomicRanges')
    io = modules::import('ebi-predocs/ebits/io')

    modules::import_package('dplyr', attach = TRUE)
    tidyr = modules::import_package('tidyr', attach = TRUE)

    all_bw_files = dir(args$coverage_path, pattern = '\\.bw$', full.names = TRUE)
    watson_bw_files = grep('-minus', all_bw_files, value = TRUE, invert = TRUE)
    crick_bw_files = grep('-minus', all_bw_files, value = TRUE)

    samples = io$read_table(args$design, header = TRUE) %>%
        filter(Lane == 1) %>%
        select(Library = Sample_ID) %>%
        mutate(Library = gsub('_', '-', Library),
               Which = ifelse(grepl('^MJ3', Library), 'MRJP­3', 'royal jelly'))

    watson_samples = samples %>%
        mutate(File = vapply(Library, grep, character(1), watson_bw_files, value = TRUE)) %>%
        mutate(Library = gsub('-', '­', Library), Strand = '+')

    crick_samples = samples %>%
        mutate(File = vapply(Library, grep, character(1), crick_bw_files, value = TRUE)) %>%
        mutate(Library = gsub('-', '­', Library), Strand = '-')

    samples = bind_rows(watson_samples, crick_samples)

    annotation = rtl$import(args$annotation)

    varroa_seqname = gr$seqnames(annotation) %>%
        `[`(grep('Varroa', gr$mcols(annotation)$gene_name)) %>%
        as.character() %>%
        head(1)

    varroa_annotation = annotation[gr$seqnames(annotation) == varroa_seqname][1]

    varroa_coverage = function (coverage) {
        result = coverage[gr$seqnames(coverage) == varroa_seqname]
        GenomeInfoDb::seqlevels(result) = varroa_seqname
        result
    }

    modules::import('./coverage_plot', attach = TRUE)

    load_coverage = function (files) {
        lapply(files, function (file) varroa_coverage(rtl$import(file)))
    }

    coverage = samples %>%
        mutate(Coverage = load_coverage(File)) %>%
        mutate(Coverage = lapply(Coverage, coverage_layout)) %>%
        select(-File) %>%
        tidyr$unnest() %>%
        mutate(Coverage = sign(Coverage) * log10(1 + abs(Coverage)))

    modules::import('klmr/ggplots', attach = TRUE)
    theme_set(theme_publication())

    nice_floor = function (n, accuracy) {
        sign(n) * floor(abs(n) / accuracy) * accuracy
    }

    y_extrema = function (range) {
        range = nice_floor(sign(range) * (10 ^ abs(range) - 1), c(10, 100))
        sign(range) * log10(1 + abs(range))
    }

    y_labels = function (x) {
        vapply(10 ^ abs(x) - 1, scales::comma, character(1L))
    }

    type_colors = c(`MRJP­3` = '#7ba700', `royal jelly` = '#007ba7')

    p = ggplot(coverage) +
        aes(Position, Coverage, fill = Which, alpha = Strand) +
        geom_ribbon(aes(ymax = Coverage), ymin = 0) +
        scale_x_genomic(multiplier = 1e3) +
        scale_y_continuous(labels = y_labels, breaks = y_extrema) +
        scale_alpha_manual(values = c(`-` = 0.75, `+` = 1), guide = FALSE) +
        scale_fill_manual(NULL, values = type_colors, guide = FALSE) +
        facet_grid(Library ~ ., scales = 'free_y') +
        xlab('VDV­1 genome position') +
        theme(axis.ticks.x = element_line())

    ggsave(args$outfile, p, width = 6, height = 4)
})

# vim: ft=r
