#!/usr/bin/env Rscript

args = list(coverage = 'data/quant/royal-jelly-counts.tsv',
            design = 'raw/samples.csv',
            viruses = 'supporting/bee-virus-list.csv',
            total_mapped = 'data/quant/all-mapped-royal-jelly-counts.tsv',
            unmapped = 'data/quant/unmapped-royal-jelly-counts.tsv',
            mirna_mapped = 'data/mirna/summary/all-counts.tsv')

sys = modules::import('klmr/sys')

sys$run({
    io = modules::import('ebi-predocs/ebits/io')

    modules::import_package('dplyr', attach = TRUE)
    tidyr = modules::import_package('tidyr')

    design = io$read_table(args$design, header = TRUE) %>%
        filter(Lane == 1) %>%
        select(Sample_ID)

    viruses = io$read_table(args$viruses) %>%
        select(Species = 1, ID = 5)

    annotation = io$read_table('raw/apis-viruses.annotation.tsv') %>%
        select(Gene = 1, Biotype = 2) %>%
        mutate(Gene = sub('^gi\\|[^|]+\\|(ref|gb)\\|([^|]+)\\|$', '\\2', Gene),
               Biotype = gsub('_', '\u00AD', Biotype)) %>%
        add_row(Gene = 'microRNA gene', Biotype = 'miRNA') %>%
        mutate(Biotype = ifelse(Biotype == 'miRNA', 'pre\u00ADmiRNA', Biotype))

    total_mapped = io$read_table(args$total_mapped) %>%
        select(Library = 1, Count = 2) %>%
        mutate(Gene = NA_character_) %>%
        select(Gene, Library, Count)

    mirna_coverage = io$read_table(args$mirna_mapped, header = FALSE) %>%
        select(Library = 1, Count = 2) %>%
        mutate(Gene = 'microRNA gene') %>%
        select(Gene, Library, Count)

    raw_coverage = io$read_table(args$coverage, header = TRUE) %>%
        tidyr$gather(Library, Count, -Gene) %>%
        bind_rows(total_mapped) %>%
        bind_rows(mirna_coverage) %>%
        mutate(Library = sub('_.*', '', Library) %>% gsub('-', '_', .)) %>%
        inner_join(design, by = c('Library' = 'Sample_ID')) %>%
        mutate(Gene = sub('^gi\\|[^|]+\\|(ref|gb)\\|([^|]+)\\|$', '\\2', Gene)) %>%
        left_join(viruses, by = c('Gene' = 'ID')) %>%
        mutate(Species = ifelse(is.na(Species), 'Apis mellifera', Species)) %>%
        mutate(Species = relevel(factor(Species), 'Apis mellifera')) %>%
        left_join(annotation, by = 'Gene') %>%
        mutate(Which = ifelse(grepl('^MJ3', Library), 'MRJP­3', 'royal jelly'))

    sum_assigned_coverage = raw_coverage %>%
        filter(! is.na(Gene), Species == 'Apis mellifera') %>%
        group_by(Library) %>%
        summarize(Count = sum(Count))

    unassigned_coverage = raw_coverage %>%
        filter(is.na(Gene)) %>%
        inner_join(sum_assigned_coverage, by = 'Library') %>%
        mutate(Count = Count.x - Count.y,
               Biotype = 'other') %>%
        select(!!! names(raw_coverage))

    coverage = raw_coverage %>%
        filter(! is.na(Gene)) %>%
        bind_rows(unassigned_coverage)

    # Calcuate size factors based on protein-coding genes only.
    size_factors = coverage %>%
        filter(Species == 'Apis mellifera',
               Biotype == 'protein\u00ADcoding') %>%
        group_by(Biotype) %>%
        mutate(LogGeometricMean = sum(log(Count[Count > 0])) / n()) %>%
        ungroup() %>%
        mutate(LogRatio = log(Count) - LogGeometricMean) %>%
        group_by(Library) %>%
        filter(is.finite(LogGeometricMean), Count > 0) %>%
        summarize(SizeFactor = exp(median(LogRatio)))

    size_factors

    # Well. Hum. These are *hugely* different, and also don’t correlate with the
    # raw read counts per library:

    read_counts_per_library = raw_coverage %>%
        filter(! is.na(Gene)) %>%
        group_by(Library) %>%
        summarize(Count = sum(Count)) %>%
        mutate(SizeFactor = Count / mean(Count)) %>%
        select(-Count)

    inner_join(size_factors, read_counts_per_library, by = 'Library') %>%
        with(cor(SizeFactor.x, SizeFactor.y, method = 'spearman'))

    # Yeah … so we’ll instead use the read counts per library as a normalisation
    # factor instead.

    size_factors = read_counts_per_library

    normalize_counts = function (.data, size_factors, join) {
        inner_join(.data, size_factors, by = join) %>%
            mutate(Count = Count / SizeFactor) %>%
            select(-SizeFactor)
    }

    compute_fractions = function (.data, ...) {
        columns = quos(...)
        .data %>%
            group_by(!!! columns) %>%
            summarize(Count = sum(Count)) %>%
            mutate(Fraction = Count / sum(Count)) %>%
            ungroup()
    }

    unmapped = io$read_table(args$unmapped) %>%
        select(Library = 1, Count = 2) %>%
        mutate(Library = sub('_.*', '', Library) %>% gsub('-', '_', .),
               Species = factor('unmapped', c(levels(coverage$Species), 'unmapped')),
               Which = ifelse(grepl('^MJ3', Library), 'MRJP­3', 'royal jelly'),
               Fraction = 1) %>%
        normalize_counts(size_factors, 'Library')

    species_coverage_pre = coverage %>%
        normalize_counts(size_factors, 'Library') %>%
        compute_fractions(Library, Which, Species) %>%
        mutate(Species = `levels<-`(Species, c(levels(Species), 'unmapped')))


    # Fudge count values of unmapped reads. This is done to get bars/points
    # that are “about right”. The bar is then broken, and the y-axis value
    # adjusted, in manual postprocessing.

    species_coverage = unmapped %>%
        mutate(Count = Count - min(Count) + max(species_coverage_pre$Count)) %>%
        bind_rows(species_coverage_pre, .)

    biotype_coverage = coverage %>%
        filter(Species == 'Apis mellifera') %>%
        normalize_counts(size_factors, 'Library') %>%
        compute_fractions(Library, Which, Biotype)

    modules::import('klmr/ggplots', attach = TRUE)
    theme_set(theme_publication())

    type_colors = c(`MRJP­3` = '#7ba700', `royal jelly` = '#007ba7')

    wrap_label = function (n) {
        function (x) mutate_all(x, funs(stringr::str_wrap(., n)))
    }

    #' Summary plot with individual points as dotplot
    #'
    #' @param bin_width the bin width to use for the dotplot
    #' @param dot_size the dot size to use for the dotplot, relative to the
    #' \code{bin_width}
    #' @param scale a \code{Scale} instance that serves as the y-axis scale
    layout_mini_bars = function (bin_width, dot_size, scale) {
        mean_fun = switch(
            scale$trans$name,
            identity = mean,
            `log-10` = function (x) log10(mean(10 ^ x)),
            stop('unsupported scale provided (not log10 or continuous)')
        )

        segment_y = switch(
            scale$trans$name,
            identity = -0.05,
            `log-10` = 1
        )

        list(
            stat_summary(fun.y = mean_fun, geom = 'bar', color = NA, alpha = 0.5),
            geom_dotplot(
                position = position_dodge(width = 0.5), width = 0.5,
                binaxis = 'y', stackdir = 'center',
                binwidth = bin_width, dotsize = dot_size,
                color = 'white'
            ),
            scale,
            scale_color_gray(NULL),
            scale_fill_gray(NULL),
            annotate(
                'segment',
                x = -Inf, xend = Inf,
                y = segment_y, yend = segment_y,
                color = 'black', size = 0.5
            ),
            coord_cartesian(expand = FALSE),
            theme(
                axis.text.x = element_blank(),
                axis.title.x = element_blank(),
                strip.text.x = element_text(vjust = 1)
            )
         )
    }

    inverse_relevel = function (x, last) {
        factor(x, levels = c(setdiff(levels(x), last), last))
    }

    multiples = function (multiplier) function (x) {
        lapply(x, function (x) x / multiplier)
    }

    powers = function (base = 10) function (x) {
        lapply(x, function (x) bquote(.(base) ^ .(log(x) / log(base))))
    }

    tidy_ttest = function (a, b) {
        broom::tidy(t.test(a, b))
    }

    significance = species_coverage %>%
        filter(grepl('Apis|Varroa', Species)) %>%
        select(-Fraction, -Library) %>%
        group_by(Which, Species) %>%
        tidyr$nest(.key = Count) %>%
        mutate(Count = lapply(Count, `[[`, 'Count')) %>%
        tidyr$spread(Species, Count) %>%
        mutate(Test = Map(tidy_ttest, `Apis mellifera`, `Varroa Destructor Virus 1`)) %>%
        tidyr$unnest(Test) %>%
        select(Which, Stat = statistic, `p-value` = p.value, conf.low, conf.high)

    significance

    # Only plot libraries which contribute at least 1% of the coverage.
    species_coverage_plot = species_coverage %>%
        group_by(Which, Species) %>%
        filter(any(Fraction >= 0.01)) %>%
        ungroup() %>%
        mutate(Species = inverse_relevel(relevel(reorder(Species, -Fraction), 'Apis mellifera'), 'unmapped')) %>%
        ggplot() +
        aes(Which, Count, color = Which, fill = Which) +
        facet_grid(. ~ Species, switch = 'x', labeller = wrap_label(15)) +
        layout_mini_bars(5e5, 0.5, scale_y_continuous('normalised RNA count (in million)', labels = multiples(1e6)))

    cow = modules::import_package('cowplot')

    annotate_significance = function (which, from, to, y) {
        p = filter(significance, grepl(which, Which))$`p-value`
        psym = unclass(symnum(
            p, corr = FALSE, na = FALSE,
            cutpoints = c(0, 0.001, 0.01, 0.05, 0.1, 1),
            symbols = c('***', '**', '*', '.', 'n.s.')
        ))

        list(
            cow$draw_line(c(from, to), c(y, y)),
            cow$draw_label(psym, x = (from + to) / 2, y = y + 0.015)
        )
    }

    cow$ggdraw(species_coverage_plot) +
        annotate_significance('MRJP', 0.11, 0.3, 0.3) +
        annotate_significance('royal jelly', 0.21, 0.41, 0.35)

    ggsave('data/plots/species-coverage-boxplot.pdf', width = 5, height = 5, useDingbats = FALSE)

    # Only plot libraries which contribute at least 0.1% of the coverage.
    normalized_biotype_coverage %>%
        group_by(Biotype) %>%
        filter(any(Fraction >= 0.001)) %>%
        ungroup() %>%
        mutate(Biotype = inverse_relevel(reorder(Biotype, -Fraction), 'other')) %>%
        ggplot() +
        aes(Which, Count, color = Which, fill = Which) +
        facet_grid(. ~ Biotype, switch = 'x', labeller = wrap_label(12)) +
        layout_mini_bars(0.2, 1, scale_y_log10('normalised RNA count', breaks = 10 ^ seq(0, 6), labels = powers()))

    ggsave('data/plots/biotype-coverage-boxplot.pdf', width = 9, height = 5, useDingbats = FALSE)
})

# vim: ft=r
