#!/usr/bin/env bash

opts="-f0x50"

case "$1" in
    -s-)
        opts="-f0x40 -F0x10"
        shift
        ;;
    -s+)
        shift
        ;;
    *)
        ;;
esac

infile="$1"
outfile="$2"

shift 2
rest="$@"

samtools view -b $opts "$infile" \
| bedtools genomecov ${rest[@]} -bg -ibam - \
| LC_COLLATE=C sort -k1,1 -k2,2n \
> "$outfile"
